# Generated by Django 3.0.3 on 2020-04-01 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sympthoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('dusznosci', models.CharField(blank=True, choices=[('t', 'Tak'), ('l', 'Lekkie'), ('n', 'Nie')], default='n', help_text='Czy wystepują duszności ?', max_length=1)),
                ('kaszel', models.CharField(blank=True, choices=[('mocny', 'Mocny'), ('lekki', 'Lekki'), ('brak', 'Brak')], default='b', help_text='Czy wystepuje kaszel  ?', max_length=5)),
                ('inne_objawy', models.CharField(help_text='Podaj inne zauważone objawy', max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
