# Generated by Django 3.0.5 on 2020-06-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_mymodelwithfigure'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModelWithFigure',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='fig',
            new_name='figure',
        ),
    ]
