# Generated by Django 3.0.5 on 2020-06-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20200605_2318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='model',
            new_name='MyModel',
        ),
    ]
