# Generated by Django 3.0.5 on 2020-06-05 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20200605_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='figure',
            new_name='fig',
        ),
    ]
