# Generated by Django 3.0.5 on 2020-06-05 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20200605_2320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
